### PR TITLE
Partially fix #203

### LINKED ISSUE #203: ScalaReflectionException in TypeBuilder
I'm trying to define an endpoint in Rho that gets passed an entity in JSON Patch format by using the definitions from [diffson-circe](https://github.com/gnieh/diffson/blob/master/circe/src/main/scala/gnieh/diffson/CirceInstance.scala):

```scala
import io.circe.generic.auto._
import org.http4s.circe._
import org.http4s.rho._
import org.http4s.rho.swagger._

object Service {

  import gnieh.diffson.circe._
  import gnieh.diffson.circe.DiffsonProtocol._

  val service: RhoService = new RhoService {
    PATCH / "hello" ^ jsonOf[JsonPatch] |>> { _: JsonPatch =>
      Ok("Hello World.")
    }
  }
}
```

When hitting the `GET /swagger.json` endpoint, the `JsonPatch` definition is missing from the spec and an exception is logged:
```
[scala-execution-context-global-63] INFO  o.h.r.s.TypeBuilder - Failed to build model for type JsonPatchSupport.this.Test
scala.ScalaReflectionException: type JsValue is not a class
	at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
	at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:94)
	at org.http4s.rho.swagger.TypeBuilder$.org$http4s$rho$swagger$TypeBuilder$$isObjectEnum(TypeBuilder.scala:144)
	at org.http4s.rho.swagger.TypeBuilder$DataType$.fromType(TypeBuilder.scala:291)
	at org.http4s.rho.swagger.TypeBuilder$.$anonfun$typeToProperty$1(TypeBuilder.scala:203)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:252)
	at org.http4s.rho.swagger.TypeBuilder$.typeToProperty(TypeBuilder.scala:185)
	at org.http4s.rho.swagger.TypeBuilder$.paramSymToProp(TypeBuilder.scala:179)
	at org.http4s.rho.swagger.TypeBuilder$.$anonfun$modelToSwagger$1(TypeBuilder.scala:160)
	at scala.collection.immutable.List.map(List.scala:287)
	at org.http4s.rho.swagger.TypeBuilder$.modelToSwagger(TypeBuilder.scala:160)
	at org.http4s.rho.swagger.TypeBuilder$.go$1(TypeBuilder.scala:70)
	at org.http4s.rho.swagger.TypeBuilder$.$anonfun$collectModels$9(TypeBuilder.scala:94)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.http4s.rho.swagger.TypeBuilder$.$anonfun$collectModels$8(TypeBuilder.scala:93)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.http4s.rho.swagger.TypeBuilder$.go$1(TypeBuilder.scala:90)
	at org.http4s.rho.swagger.TypeBuilder$.$anonfun$collectModels$6(TypeBuilder.scala:80)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at org.http4s.rho.swagger.TypeBuilder$.go$1(TypeBuilder.scala:74)
	at org.http4s.rho.swagger.TypeBuilder$.collectModels(TypeBuilder.scala:103)
	at org.http4s.rho.swagger.TypeBuilder$.collectModels(TypeBuilder.scala:23)
	at org.http4s.rho.swagger.SwaggerModelsBuilder.$anonfun$collectDefinitions$1(SwaggerModelsBuilder.scala:51)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at org.http4s.rho.swagger.SwaggerModelsBuilder.collectDefinitions(SwaggerModelsBuilder.scala:51)
	at org.http4s.rho.swagger.SwaggerModelsBuilder.mkSwagger(SwaggerModelsBuilder.scala:25)
	at org.http4s.rho.swagger.SwaggerSupport$.$anonfun$createSwagger$1(SwaggerSupport.scala:44)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at org.http4s.rho.swagger.SwaggerSupport$.createSwagger(SwaggerSupport.scala:44)
	at org.http4s.rho.swagger.SwaggerSupport$.swaggerSpec$lzycompute$1(SwaggerSupport.scala:27)
	at org.http4s.rho.swagger.SwaggerSupport$.swaggerSpec$1(SwaggerSupport.scala:25)
	at org.http4s.rho.swagger.SwaggerSupport$.$anonfun$apply$2(SwaggerSupport.scala:31)
	at org.http4s.rho.swagger.SwaggerSupport$$anon$1.response$lzycompute(SwaggerSupport.scala:58)
	at org.http4s.rho.swagger.SwaggerSupport$$anon$1.response(SwaggerSupport.scala:55)
	at org.http4s.rho.swagger.SwaggerSupport$$anon$1.$anonfun$new$1(SwaggerSupport.scala:61)
	at shapeless.ops.FnToProductInstances$$anon$1.$anonfun$apply$1(fntoproduct.scala:37)
	at org.http4s.rho.bits.HListToFunc$$anon$2.$anonfun$conv$2(HListToFunc.scala:35)
	at org.http4s.rho.bits.PathTree$.$anonfun$makeLeaf$2(PathTree.scala:85)
	at org.http4s.rho.bits.ResultResponse.map(ResultResponse.scala:34)
	at org.http4s.rho.bits.ResultResponse.map$(ResultResponse.scala:33)
	at org.http4s.rho.bits.SuccessResponse.map(ResultResponse.scala:50)
	at org.http4s.rho.bits.PathTree$.$anonfun$makeLeaf$1(PathTree.scala:84)
	at org.http4s.rho.bits.PathTree$SingleLeaf.attempt(PathTree.scala:125)
	at org.http4s.rho.bits.PathTree$Node.walk(PathTree.scala:247)
	at org.http4s.rho.bits.PathTree$Node.walk$(PathTree.scala:212)
	at org.http4s.rho.bits.PathTree$MatchNode.walk(PathTree.scala:264)
	at org.http4s.rho.bits.PathTree$Node.walk(PathTree.scala:222)
	at org.http4s.rho.bits.PathTree$Node.walk$(PathTree.scala:212)
	at org.http4s.rho.bits.PathTree$MatchNode.walk(PathTree.scala:264)
	at org.http4s.rho.bits.PathTree$Node.walkTree(PathTree.scala:208)
	at org.http4s.rho.bits.PathTree$Node.walkTree$(PathTree.scala:206)
	at org.http4s.rho.bits.PathTree$MatchNode.walkTree(PathTree.scala:264)
	at org.http4s.rho.bits.PathTree.getResult(PathTree.scala:45)
	at org.http4s.rho.CompileService$.$anonfun$foldServices$2(CompileService.scala:44)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
	at cats.data.KleisliSemigroup.$anonfun$combine$1(Kleisli.scala:254)
	at cats.data.Kleisli.apply(Kleisli.scala:63)
	at org.http4s.server.Router$.$anonfun$define$3(Router.scala:35)
	at org.http4s.server.blaze.Http1ServerStage.liftedTree1$1(Http1ServerStage.scala:107)
	at org.http4s.server.blaze.Http1ServerStage.$anonfun$runRequest$2(Http1ServerStage.scala:107)
	at fs2.Strategy$$anon$3$$anon$4.run(Strategy.scala:54)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### PR DESCRIPTION
**Pull request by RafalSumislawski**
Add missing sym.isClass check in isObjectEnum

Add tests for partially working shapeless coproducts and classes parametrised by type parameter of an outer type.

### CODE REVIEW

File: swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala [hunk 1]
```diff
@@ -403,6 +411,18 @@ class TypeBuilderSpec extends Specification {
...
     }
+
+    "Build a model for a class using type parameters of an outer class" in {
+      val ms = modelOf[OuterString.Inner]
+      ms.size must_!== 0 // At least try to return some model.
+      // It won't be a fully correct model since TypeBuilder will fail to resolve the type param T to a concrete type.
+    }
+
+    "Build a model for shapless coproduct (:+:)" in {
+      val ms = modelOf[ShapelessIntOrString]
```
Comment (zarthross) [inline swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala]: I printed the model for this one and it was.... not great.  Its awesome though that it doesn't explode.  I'll open an issue to add first class shapeless `Coproduct` swagger support.

Comment (zarthross) [reply swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala]: Issue #283 to correct the model.

File: swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala [hunk 2]
```diff
@@ -403,6 +411,18 @@ class TypeBuilderSpec extends Specification {
       modelOf[FooEither] must not(throwA[StackOverflowError])
       modelOf[FooEither].size must_== 1
     }
+
+    "Build a model for a class using type parameters of an outer class" in {
+      val ms = modelOf[OuterString.Inner]
+      ms.size must_!== 0 // At least try to return some model.
+      // It won't be a fully correct model since TypeBuilder will fail to resolve the type param T to a concrete type.
```
[the remark this answers is not in the document]
Comment (RafalSumislawski) [reply swagger/src/test/scala/org/http4s/rho/swagger/TypeBuilderSpec.scala]: You're right. For Outer[String], the model is accidentally correct, the description is not a problem. I could have done better job choosing the test data. If we go with Outer[Int] the problem will be more apparent:
```
  case class FooInt(t: Int)
  object OuterInt extends Outer[Int]
```
```
Set(ModelImpl(org.http4s.rho.swagger.model.FooInt,     FooInt,Some(FooInt),Some(object),None,List(),Map(t -> AbstractProperty(integer,None,true,None,None,                                      Some(int32))),false,None,None,None,None))
Set(ModelImpl(org.http4s.rho.swagger.model.Outer.Inner,Inner, Some(Inner), Some(object),None,List(),Map(t -> AbstractProperty(string, None,true,None,Some(org.http4s.rho.swagger.model.Outer.T),None)),       false,None,None,None,None))
```
Now the property `t` which was supposed to be an `integer/int32` is a `string` and that is a bad thing.

 I'll adapt the test case to show more clearly where the problem it.

**Comment by zarthross** [comment]
@RafalSumislawski I just pushed a commit that I think fixes the support for that fully.  Let me know if you have any issues with it.

**Comment by RafalSumislawski** [comment]
Looks very good :+1:

**Comment by zarthross** [comment]
Appears to fail the scala 2.11 build... looking into why now....

**Comment by RafalSumislawski** [comment]
Looks fine :+1:
