### PR TITLE
Check for errors on model building and support Process and Task results

### LINKED ISSUE #69: java.util.NoSuchElementException: head of empty list
```
> rho-examples[ERROR] java.util.NoSuchElementException: head of empty list
rho-examples[ERROR] 	at scala.collection.immutable.Nil$.head(List.scala:420)
rho-examples[ERROR] 	at scala.collection.immutable.Nil$.head(List.scala:417)
rho-examples[ERROR] 	at org.http4s.rho.swagger.SwaggerModelsBuilder.mkCollectionProperty$1(SwaggerModelsBuilder.scala:244)
rho-examples[ERROR] 	at org.http4s.rho.swagger.SwaggerModelsBuilder.org$http4s$rho$swagger$SwaggerModelsBuilder$$typeToProp$1(SwaggerModelsBuilder.scala:229)
rho-examples[ERROR] 	at org.http4s.rho.swagger.SwaggerModelsBuilder$$anonfun$mkResponse$1.apply(SwaggerModelsBuilder.scala:256)
rho-examples[ERROR] 	at org.http4s.rho.swagger.SwaggerModelsBuilder$$anonfun$mkResponse$1.apply(SwaggerModelsBuilder.scala:256)
rho-examples[ERROR] 	at scala.Option.map(Option.scala:146)
...
```

### PR DESCRIPTION
**Pull request by bryce-anderson**
closes #69 

@cencarnacion, I noticed you've pushed a fix for the same issue.

### CODE REVIEW

**Comment by cencarnacion** [comment]
It looks good!

File: swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala [hunk 1]
```diff
@@ -240,20 +250,27 @@ private[swagger] class SwaggerModelsBuilder(formats: SwaggerFormats) {
...
+          RefProperty(ref = param.simpleName).some 
 
-      ArrayProperty(items = prop)
+      prop.map(p => ArrayProperty(items = p))
     }
 
-    code -> Response(description = descr, schema = otpe.map(typeToProp))
+    val schema = {
+      try otpe.flatMap(typeToProp)
+      catch { case _: Throwable =>
```
Comment (LeifW) [inline swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala]: Wouldn't we want a more specific catch here? At least not `Throwable`?

Comment (bryce-anderson) [inline swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala]: Yes, in hindsight maybe NonFatal would have been better. Perhaps logging
the error or at least the message and type would be good too.
